name: language_learning_app
description: A demo language learning app (Spanish/French flashcards, progress, mnemonics, and more) for BOOM-08.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
